export const MIN_REACTIVE_SENSOR_INTERVAL_MS = 100
export const REACTIVE_SENSOR_SOFT_TIMEOUT_MS = 500
export const REACTIVE_SENSOR_RESPONSE_TIMEOUT_MS = 900
export const REACTIVE_BUTTON_RESPONSE_TIMEOUT_MS = 250
export const MEMORY_RESPONSE_SYNC_TIMEOUT_MS = 250
export const REACTIVE_BUTTON_BLOCKING_BUDGET_MS =
  REACTIVE_BUTTON_RESPONSE_TIMEOUT_MS + MEMORY_RESPONSE_SYNC_TIMEOUT_MS
